channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - pytest=7.1.2
  - nodejs
  - pip=19
  - pip:
    - git+https://github.com/mskcc/toil.git@5.4.2#egg=toil[cwl]
    - cwlref-runner==1.0
    - sphinx==4.0.2

